// Generated by CoffeeScript 1.10.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.coffee = function(input) {
    var caffeine, caffeineMsg, i, j, len, limit, overTheLimit, overTheLimitMsg, results, underTheLimitMsg;
    input = document.getElementsByName("cups");
    results = [];
    for (j = 0, len = input.length; j < len; j++) {
      i = input[j];
      if (i.checked) {
        caffeine = i.value * 95;
        caffeineMsg = "You've had " + caffeine + " milligrams of caffeine today!";
        document.getElementById("caffeine").innerHTML = caffeineMsg;
        limit = 400 - caffeine;
        overTheLimit = limit * -1;
        if (limit > 0) {
          underTheLimitMsg = "You're still " + limit + " milligrams of caffeine under the daily recommended dose. Have another cup!";
          results.push(document.getElementById("limit").innerHTML = underTheLimitMsg);
        } else {
          overTheLimitMsg = "That's " + overTheLimit + " milligrams of caffeine over the daily recommended dose. That's enough for today!";
          results.push(document.getElementById("limit").innerHTML = overTheLimitMsg);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

}).call(this);
